; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = m5paper

[common]
build_flags = 
	-std=gnu++17
	-I include_global
	-D PNGLE_GRAYSCALE_OUTPUT=1
	-D PNGLE_NO_GAMMA_CORRECTION=1
build_unflags = 
	-std=gnu++11

[m5paper_common]
platform = espressif32
board = m5stack-fire
framework = espidf
monitor_speed = 115200
upload_speed = 1500000
monitor_filters = colorize
board_build.partitions = partitions.csv
board_build.f_cpu = 240000000L
build_flags = 
	-O3
	${common.build_flags}
	-D CONFIG_SPIRAM_CACHE_WORKAROUND
	-D EPUB_INKPLATE_BUILD=1
	-D EPUB_LINUX_BUILD=0
	-D BOARD_TYPE_M5PAPER
	-D INCLUDE_vTaskSuspend=1
	-D SHOW_TIMING=0
	-D DATE_TIME_RTC=1
	-I lib/externals
	-I lib_freetype/include/freetype2
	-L lib_freetype/lib
	-lfreetype
build_unflags = 
	${common.build_unflags}
lib_extra_dirs = 
	lib_esp32
board_build.embed_files = 
	src/embed/favicon.ico
	src/embed/upload_script.html
lib_deps = 
	m5stack/M5EPD@^0.1.5

[env:m5paper]
extends = m5paper_common
build_type = release
build_flags = 
	-D EPUB_LOG_LEVEL=ESP_LOG_INFO
	${m5paper_common.build_flags}

